library(readxl)
library(RColorBrewer)
library(psych)
library(sqldf)
library(plotrix)
library(ResourceSelection)
library(car)
library(ROCR)
library(caret)
set.seed(123)
z1<-read_excel("D:\\DATA ANALYSIS\\PROJECT\\UNITED INDIA INSURANCE\\Insurance Data.xlsx")
str(z1)
colSums(is.na(z1))
#View(z1)
############################# AGE ####################
median(z1$Age,na.rm=T)
mean(z1$Age,na.rm = T)
z1$Age<-ifelse(is.na(z1$Age),median(z1$Age,na.rm=T),z1$Age)
median(z1$Age)
table(z1$Age)
windows(height = 7,width = 4.5)
barplot(table(z1$Age),xlab="Age",ylab="Frequency",ylim=c(0,2500),col=brewer.pal(n=8,"OrRd"))
s1<-sqldf("select age,count(age) from z1 group by age")
s1
############################ GENDER #################
table(z1$Gender)
z1$Gender<-ifelse(is.na(z1$Gender),"M",z1$Gender)
table(z1$Gender)
windows(height = 7,width = 4.5)
pie3D(table(z1$Gender),explode = 0.1,col=brewer.pal(n=2,"Dark2"))
legend("topright",c("Female","Male"),fill=brewer.pal(n=2,"Dark2"))
s2<-sqldf("select count(current_product) from z1 where current_product=='Yes' and gender=='F'")
s2
############################ MARITAL STATUS #########
table(z1$`Marital_Status`)
z1$`Marital_Status`<-ifelse(is.na(z1$`Marital_Status`),"Married",z1$`Marital_Status`)
table(z1$`Marital_Status`)
windows(height = 7,width = 4.5)
pie3D(table(z1$Marital_Status),explode = 0.1,col=brewer.pal(n=3,"Reds"))
legend("topright",c("Divorced","Married","Single"),fill=brewer.pal(n=3,"Reds"))
colSums(is.na(z1))
s3<-sqldf("select count(current_product) from z1 where current_product=='Yes' and marital_status=='Divorced'")
s3
###################### FAMILY MEMBERS #############
median(z1$`Family_Members`,na.rm=T)
z1$`Family_Members`<-ifelse(is.na(z1$`Family_Members`),median(z1$`Family_Members`,na.rm=T),z1$`Family_Members`)
median(z1$`Family_Members`)
colSums(is.na(z1))
table(z1$Family_Members)
barplot(table(z1$Family_Members),xlab="Family Members",ylab="Frequency",col=brewer.pal(n=8,"YlOrRd"))
#################### EDUCATION ###################
str(z1$Education)
table(z1$Education)
z1$Education<-ifelse(is.na(z1$Education),"BD",z1$Education)
table(z1$Education)
windows(height = 7,width = 4.5)
pie3D(table(z1$Education),explode = 0.1,col=brewer.pal(n=6,"Reds"))
legend("topright",c("BD","LHS","MD","NE","PD","UHS"),cex = 0.9,fill=brewer.pal(n=6,"Reds"))
################### OCCUPATION ##################
str(z1$Occupation)
table(z1$Occupation)
z1$Occupation<-ifelse(is.na(z1$Occupation),"SPT",z1$Occupation)
table(z1$Occupation)
windows(height = 7,width = 4.5)
pie3D(table(z1$Occupation),explode = 0.1,col=brewer.pal(n=3,"BuGn"))
legend("topright",c("SE","SFT","SPT"),fill=brewer.pal(n=3,"BuGn"))
colSums(is.na(z1))
################### JOB TITLE ##################
str(z1$`Job_Title`)
table(z1$`Job_Title`)
z1$`Job_Title`<-ifelse(is.na(z1$`Job_Title`),"FH",z1$`Job_Title`)
table(z1$`Job_Title`)
windows(height = 7,width = 4.5)
barplot(table(z1$Job_Title),xlab="Job Titles",ylab = "Frequency",ylim=c(0,25000),col=brewer.pal(n=4,"Blues"))
colSums(is.na(z1))
################## INCOME #####################
str(z1$Income)
mean(z1$Income,na.rm=T)
median(z1$Income,na.rm=T)
max(z1$Income,na.rm=T)
min(z1$Income,na.rm=T)
z1$Income<-ifelse(is.na(z1$Income),mean(z1$Income,na.rm=T),z1$Income)
mean(z1$Income)
median(z1$Income)
colSums(is.na(z1))
################# CURRENT PRODUCT #############
str(z1$`Current_Product`)
table(z1$`Current_Product`)
z1$`Current_Product`<-ifelse(is.na(z1$`Current_Product`),"Yes",z1$`Current_Product`)
table(z1$`Current_Product`)
windows(height = 7,width = 4.5)
pie3D(table(z1$Current_Product),explode = 0.1,col=brewer.pal(n=2,"Greens"))
legend("topright",c("No","Yes"),fill=brewer.pal(n=2,"Greens"))
colSums(is.na(z1))
################## CURRENT PRODUCT TYPE ##########
str(z1$`Current_Product_Type`)
table(z1$`Current_Product_Type`)
z1$`Current_Product_Type`<-ifelse(is.na(z1$`Current_Product_Type`),"NA",z1$`Current_Product_Type`)
table(z1$`Current_Product_Type`)
barplot(table(z1$Current_Product_Type),xlab="Current Product Type",ylab="Frequency",col=brewer.pal(n=6,"Blues"))
colSums(is.na(z1))
names(z1)
################# CURRENT COVERAGE ##############
str(z1$Current_Coverage)
mean(z1$Current_Coverage,na.rm=T)
median(z1$Current_Coverage,na.rm = T)
z1$Current_Coverage<-ifelse(is.na(z1$Current_Coverage),median(z1$Current_Coverage,na.rm=T),z1$Current_Coverage)
mean(z1$Current_Coverage)
median(z1$Current_Coverage)
table(z1$Current_Coverage)
barplot(table(z1$Current_Coverage),col=brewer.pal(n=8,"Blues"))
colSums(is.na(z1))
################# NEW PRODUCT TYPE #############
str(z1$New_Product_Type)
table(z1$New_Product_Type)
z1$New_Product_Type<-ifelse(is.na(z1$New_Product_Type),"ANS",z1$New_Product_Type)
table(z1$New_Product_Type)
windows(height = 7,width = 4.5)
#pie3D(table(z1$New_Product_Type),explode = 0.1,col=brewer.pal(n=5,"Greens"))
#legend("topright",c("ANS","END","INV","PMT","TLE"),fill=brewer.pal(n=5,"Greens"))
barplot(table(z1$New_Product_Type),col=brewer.pal(n=5,"Blues"))
colSums(is.na(z1))
################ NEW COVERAGE #################
str(z1$New_Coverage)
mean(z1$New_Coverage,na.rm=T)
median(z1$New_Coverage,na.rm=T)
z1$New_Coverage<-ifelse(is.na(z1$New_Coverage),mean(z1$New_Coverage,na.rm=T),z1$New_Coverage)
mean(z1$New_Coverage)
median(z1$New_Coverage)
table(z1$New_Coverage)
barplot(table(z1$New_Coverage),col=brewer.pal(n=7,"Greens"),xlab="New Coverage",ylab="Amount")
colSums(is.na(z1))
################ RATING ##############
str(z1$Rating)
table(z1$Rating)
z1$Rating<-ifelse(is.na(z1$Rating),"Cold",z1$Rating)
table(z1$Rating)
windows(height = 7,width = 4.5)
pie3D(table(z1$Rating),explode = 0.1,col=brewer.pal(n=3,"Blues"))
legend("topright",c("Cold","Hot","Warm"),fill=brewer.pal(n=3,"Blues"))
colSums(is.na(z1))
############### CONVERTED #############
str(z1$Converted)
table(z1$Converted)
z1$Converted<-z1$Status
barplot(table(z1$Converted),col = brewer.pal(n=8,"Blues"))

#############################################################################
#############################################################################

##################################### DATA PREPARATION ##############################################
set.seed(123)
z1$Gender<-ifelse(z1$Gender=="M",1,0)
str(z1$Gender)
z1$Marital_Status<-ifelse(z1$Marital_Status=="Single",0,ifelse(z1$Marital_Status=="Married",1,2))
str(z1$Education)
z1$Education<-as.factor(z1$Education)
z1$Education<-as.integer(z1$Education)
str(z1$Occupation)
table(z1$Occupation)
z1$Occupation<-ifelse(z1$Occupation=="SE",0,ifelse(z1$Occupation=="SFT",1,2))
table(z1$Job_Title)
z1$Job_Title<-as.factor(z1$Job_Title)
z1$Job_Title<-as.integer(z1$Job_Title)
table(z1$Current_Product)
z1$Current_Product<-ifelse(z1$Current_Product=="No",0,1)
table(z1$Current_Product_Type)
z1$Current_Product_Type<-as.factor(z1$Current_Product_Type)
z1$Current_Product_Type<-as.integer(z1$Current_Product_Type)
table(z1$New_Product_Type)
z1$New_Product_Type<-as.factor(z1$New_Product_Type)
z1$New_Product_Type<-as.integer(z1$New_Product_Type)
table(z1$Rating)
z1$Rating<-ifelse(z1$Rating=="Cold",0,ifelse(z1$Rating=="Warm",1,2))
table(z1$Converted)
z1$Converted<-as.factor(z1$Converted)
z1$Converted<-as.integer(z1$Converted)
z2<-subset(z1,select = -Status)
View(z2)
write.csv(z2,"D:\\DATA ANALYSIS\\PROJECT\\UNITED INDIA INSURANCE\\EXPLORATION AND MODELLING\\NEWDATA.csv")
##############################################################################
##############################################################################






